// convert RGB (as generated by Skeleton) to hex with r'("\d{1,3} \d{1,3} \d{1,3}"), // (#.{6})' -> r'"$2", // $1'
// Usage: rgb(var(--color-primary-500)) -> var(--color-primary-500)

export const zotmeetTheme = {
  name: "zotmeet-theme",
  properties: {
    // =~= Theme Properties =~=
    "--theme-font-family-base": `system-ui`,
    "--theme-font-family-heading": `system-ui`,
    "--theme-font-color-base": "0 0 0",
    "--theme-font-color-dark": "255 255 255",
    "--theme-rounded-base": "9999px",
    "--theme-rounded-container": "8px",
    "--theme-border-base": "1px",
    // =~= Theme On-X Colors =~=
    "--on-primary": "0 0 0",
    "--on-secondary": "0 0 0",
    "--on-tertiary": "0 0 0",
    "--on-success": "255 255 255",
    "--on-warning": "255 255 255",
    "--on-error": "255 255 255",
    "--on-surface": "0 0 0",
    // =~= Theme Colors  =~=
    // primary | #7f9cd7
    "--color-primary-50": "#ecf0f9", // "236 240 249"
    "--color-primary-100": "#e5ebf7", // "229 235 247"
    "--color-primary-200": "#dfe6f5", // "223 230 245"
    "--color-primary-300": "#ccd7ef", // "204 215 239"
    "--color-primary-400": "#a5bae3", // "165 186 227"
    "--color-primary-500": "#7f9cd7", // "127 156 215"
    "--color-primary-600": "#728cc2", // "114 140 194"
    "--color-primary-700": "#5f75a1", // "95 117 161"
    "--color-primary-800": "#4c5e81", // "76 94 129"
    "--color-primary-900": "#3e4c69", // "62 76 105"
    // secondary | #7c6dc9
    "--color-secondary-50": "#ebe9f7", // "235 233 247"
    "--color-secondary-100": "#e5e2f4", // "229 226 244"
    "--color-secondary-200": "#dedbf2", // "222 219 242"
    "--color-secondary-300": "#cbc5e9", // "203 197 233"
    "--color-secondary-400": "#a399d9", // "163 153 217"
    "--color-secondary-500": "#7c6dc9", // "124 109 201"
    "--color-secondary-600": "#7062b5", // "112 98 181"
    "--color-secondary-700": "#5d5297", // "93 82 151"
    "--color-secondary-800": "#4a4179", // "74 65 121"
    "--color-secondary-900": "#3d3562", // "61 53 98"
    // tertiary | #729597
    "--color-tertiary-50": "#eaefef", // "234 239 239"
    "--color-tertiary-100": "#e3eaea", // "227 234 234"
    "--color-tertiary-200": "#dce5e5", // "220 229 229"
    "--color-tertiary-300": "#c7d5d5", // "199 213 213"
    "--color-tertiary-400": "#9cb5b6", // "156 181 182"
    "--color-tertiary-500": "#729597", // "114 149 151"
    "--color-tertiary-600": "#678688", // "103 134 136"
    "--color-tertiary-700": "#567071", // "86 112 113"
    "--color-tertiary-800": "#44595b", // "68 89 91"
    "--color-tertiary-900": "#38494a", // "56 73 74"
    // success | #0d5912
    "--color-success-50": "#dbe6db", // "219 230 219"
    "--color-success-100": "#cfded0", // "207 222 208"
    "--color-success-200": "#c3d6c4", // "195 214 196"
    "--color-success-300": "#9ebda0", // "158 189 160"
    "--color-success-400": "#568b59", // "86 139 89"
    "--color-success-500": "#0d5912", // "13 89 18"
    "--color-success-600": "#0c5010", // "12 80 16"
    "--color-success-700": "#0a430e", // "10 67 14"
    "--color-success-800": "#08350b", // "8 53 11"
    "--color-success-900": "#062c09", // "6 44 9"
    // warning | #7e7020
    "--color-warning-50": "#eceade", // "236 234 222"
    "--color-warning-100": "#e5e2d2", // "229 226 210"
    "--color-warning-200": "#dfdbc7", // "223 219 199"
    "--color-warning-300": "#cbc6a6", // "203 198 166"
    "--color-warning-400": "#a59b63", // "165 155 99"
    "--color-warning-500": "#7e7020", // "126 112 32"
    "--color-warning-600": "#71651d", // "113 101 29"
    "--color-warning-700": "#5f5418", // "95 84 24"
    "--color-warning-800": "#4c4313", // "76 67 19"
    "--color-warning-900": "#3e3710", // "62 55 16"
    // error | #a41e1e
    "--color-error-50": "#f1dddd", // "241 221 221"
    "--color-error-100": "#edd2d2", // "237 210 210"
    "--color-error-200": "#e8c7c7", // "232 199 199"
    "--color-error-300": "#dba5a5", // "219 165 165"
    "--color-error-400": "#bf6262", // "191 98 98"
    "--color-error-500": "#a41e1e", // "164 30 30"
    "--color-error-600": "#941b1b", // "148 27 27"
    "--color-error-700": "#7b1717", // "123 23 23"
    "--color-error-800": "#621212", // "98 18 18"
    "--color-error-900": "#500f0f", // "80 15 15"
    // surface | #9c9c9c
    "--color-surface-50": "#f0f0f0", // "240 240 240"
    "--color-surface-100": "#ebebeb", // "235 235 235"
    "--color-surface-200": "#e6e6e6", // "230 230 230"
    "--color-surface-300": "#d7d7d7", // "215 215 215"
    "--color-surface-400": "#bababa", // "186 186 186"
    "--color-surface-500": "#9c9c9c", // "156 156 156"
    "--color-surface-600": "#8c8c8c", // "140 140 140"
    "--color-surface-700": "#757575", // "117 117 117"
    "--color-surface-800": "#5e5e5e", // "94 94 94"
    "--color-surface-900": "#4c4c4c", // "76 76 76"
  },
};

export default zotmeetTheme;
