/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from "ts-interface-checker";
export declare const TDevmoji: t.TIface;
export declare const ConfigOptions: t.TIface;
declare const exportedTypeSuite: t.ITypeSuite;
export default exportedTypeSuite;
