// Auto-generated by scripts/fetch-room-images.ts
// Run `pnpm tsx scripts/fetch-room-images.ts` to regenerate (77/144 rooms have images)
export const ROOM_IMAGES: Record<string, string> = {
	"34680":
		"https://libapps.s3.amazonaws.com/accounts/190801/images/ALP_2510.jpg",
	"34681":
		"https://libapps.s3.amazonaws.com/accounts/190801/images/ALP_2210.jpg",
	"34682":
		"https://libapps.s3.amazonaws.com/accounts/190801/images/ALP_2610.jpg",
	"34683":
		"https://libapps.s3.amazonaws.com/accounts/190801/images/ALP_2710.jpg",
	"37288":
		"https://libapps.s3.amazonaws.com/accounts/190523/images/ALP3710.JPG",
	"37289":
		"https://libapps.s3.amazonaws.com/accounts/190523/images/ALP_3720.JPG",
	"37290":
		"https://libapps.s3.amazonaws.com/accounts/190523/images/ALP_3730.JPG",
	"37291":
		"https://libapps.s3.amazonaws.com/accounts/190523/images/ALP_3740.JPG",
	"37292":
		"https://libapps.s3.amazonaws.com/accounts/190523/images/ALP_3750.JPG",
	"44667":
		"https://libapps.s3.amazonaws.com/accounts/88849/images/PXL_20220927_152801735.MP_75.jpg",
	"44668": "https://s3.amazonaws.com/libapps/customers/926/images/ASL_586_.jpg",
	"44669": "https://s3.amazonaws.com/libapps/customers/926/images/ASL_586_.jpg",
	"44670": "https://s3.amazonaws.com/libapps/customers/926/images/ASL_586_.jpg",
	"44671": "https://s3.amazonaws.com/libapps/customers/926/images/ASL_586_.jpg",
	"44672": "https://s3.amazonaws.com/libapps/customers/926/images/ASL_586_.jpg",
	"44673": "https://s3.amazonaws.com/libapps/customers/926/images/ASL_586_.jpg",
	"44674": "https://s3.amazonaws.com/libapps/customers/926/images/ASL_586_.jpg",
	"44675": "https://s3.amazonaws.com/libapps/customers/926/images/ASL_586_.jpg",
	"44676": "https://s3.amazonaws.com/libapps/customers/926/images/ASL_586_.jpg",
	"44677": "https://s3.amazonaws.com/libapps/customers/926/images/ASL_586_.jpg",
	"44678": "https://s3.amazonaws.com/libapps/customers/926/images/ASL_586_.jpg",
	"44679": "https://s3.amazonaws.com/libapps/customers/926/images/ASL_586_.jpg",
	"44680": "https://s3.amazonaws.com/libapps/customers/926/images/ASL_586_.jpg",
	"44681": "https://s3.amazonaws.com/libapps/customers/926/images/ASL_586_.jpg",
	"44683":
		"https://libapps.s3.amazonaws.com/accounts/88849/images/PXL_20220927_152801735.MP_75.jpg",
	"44684":
		"https://libapps.s3.amazonaws.com/accounts/88849/images/PXL_20220927_152801735.MP_75.jpg",
	"44685":
		"https://libapps.s3.amazonaws.com/accounts/88849/images/PXL_20220927_152801735.MP_75.jpg",
	"44686":
		"https://libapps.s3.amazonaws.com/accounts/88849/images/PXL_20220927_152801735.MP_75.jpg",
	"44687":
		"https://libapps.s3.amazonaws.com/accounts/88849/images/PXL_20220927_152801735.MP_75.jpg",
	"44688":
		"https://libapps.s3.amazonaws.com/accounts/88849/images/PXL_20220927_152801735.MP_75.jpg",
	"44689":
		"https://libapps.s3.amazonaws.com/accounts/88849/images/PXL_20220927_152801735.MP_75.jpg",
	"44690":
		"https://libapps.s3.amazonaws.com/accounts/88849/images/PXL_20220927_152801735.MP_75.jpg",
	"44691":
		"https://libapps.s3.amazonaws.com/accounts/88849/images/PXL_20220927_152801735.MP_75.jpg",
	"44693": "https://s3.amazonaws.com/libapps/customers/926/images/ASL_586_.jpg",
	"44694": "https://s3.amazonaws.com/libapps/customers/926/images/ASL_586_.jpg",
	"44695": "https://s3.amazonaws.com/libapps/customers/926/images/ASL_586_.jpg",
	"44696": "https://s3.amazonaws.com/libapps/accounts/86460/images/LL_392.jpg",
	"44697": "https://s3.amazonaws.com/libapps/accounts/86460/images/LL_382.jpg",
	"44698": "https://s3.amazonaws.com/libapps/accounts/86460/images/LL_392.jpg",
	"44699": "https://s3.amazonaws.com/libapps/accounts/86460/images/LL_392.jpg",
	"44700": "https://s3.amazonaws.com/libapps/accounts/86460/images/LL_392.jpg",
	"44701": "https://s3.amazonaws.com/libapps/accounts/86460/images/LL_392.jpg",
	"44702": "https://s3.amazonaws.com/libapps/accounts/86460/images/LL_392.jpg",
	"44703": "https://s3.amazonaws.com/libapps/accounts/86460/images/LL_392.jpg",
	"44704": "https://s3.amazonaws.com/libapps/accounts/86460/images/LGSC-1.jpg",
	"44705": "https://s3.amazonaws.com/libapps/accounts/86460/images/LGSC-1.jpg",
	"44706": "https://s3.amazonaws.com/libapps/accounts/86460/images/LGSC-1.jpg",
	"44707": "https://s3.amazonaws.com/libapps/accounts/86460/images/LGSC-1.jpg",
	"44708": "https://s3.amazonaws.com/libapps/accounts/86460/images/LGSC-1.jpg",
	"44709": "https://s3.amazonaws.com/libapps/accounts/86460/images/LGSC-1.jpg",
	"44710": "https://s3.amazonaws.com/libapps/accounts/86460/images/LGSC-1.jpg",
	"44711": "https://s3.amazonaws.com/libapps/accounts/86460/images/LGSC-11.jpg",
	"44712": "https://s3.amazonaws.com/libapps/accounts/86460/images/LGSC-11.jpg",
	"44713": "https://s3.amazonaws.com/libapps/accounts/86460/images/LGSC-1.jpg",
	"44714": "https://s3.amazonaws.com/libapps/accounts/86460/images/LGSC-1.jpg",
	"44717": "https://libapps.s3.amazonaws.com/accounts/144488/images/SL172.jpg",
	"44718":
		"https://libapps.s3.amazonaws.com/accounts/144488/images/SL173April2022.jpg",
	"51792":
		"https://libapps.s3.amazonaws.com/accounts/144488/images/mrc_pres_studio_2.jpg",
	"59309":
		"https://libapps.s3.amazonaws.com/accounts/144488/images/SL174SPq2022_0.jpg",
	"102070":
		"https://d2jv02qf7xgjwx.cloudfront.net/accounts/88849/images/presentation_studio_study_space_locator.jpg",
	"111030":
		"https://s3.amazonaws.com/libapps/customers/926/images/ASL_586_.jpg",
	"111031":
		"https://libapps.s3.amazonaws.com/accounts/88849/images/PXL_20220927_152801735.MP_75.jpg",
	"117629":
		"https://libapps.s3.amazonaws.com/accounts/157453/images/20210907_101945.jpg",
	"117634":
		"https://libapps.s3.amazonaws.com/accounts/157453/images/20210907_101945.jpg",
	"131259":
		"https://libapps.s3.amazonaws.com/accounts/88849/images/DSC07786__1_.jpg",
	"131264": "https://libapps.s3.amazonaws.com/accounts/88849/images/LL360.jpg",
	"155343":
		"https://libapps.s3.amazonaws.com/accounts/88849/images/IMG_2499.jpg",
	"155344":
		"https://libapps.s3.amazonaws.com/accounts/88849/images/IMG_2499.jpg",
	"168432":
		"https://libapps.s3.amazonaws.com/accounts/88849/images/IMG_2499.jpg",
	"168433":
		"https://libapps.s3.amazonaws.com/accounts/88849/images/IMG_2499.jpg",
	"168434":
		"https://libapps.s3.amazonaws.com/accounts/88849/images/IMG_2499.jpg",
	"168435":
		"https://libapps.s3.amazonaws.com/accounts/88849/images/IMG_2499.jpg",
	"168436":
		"https://libapps.s3.amazonaws.com/accounts/88849/images/IMG_2499.jpg",
	"168437":
		"https://libapps.s3.amazonaws.com/accounts/88849/images/IMG_2499.jpg",
	"168438":
		"https://libapps.s3.amazonaws.com/accounts/88849/images/IMG_2499.jpg",
	"178733":
		"https://d2jv02qf7xgjwx.cloudfront.net/accounts/88849/images/IMG_2499.jpg",
	"178734":
		"https://d2jv02qf7xgjwx.cloudfront.net/accounts/88849/images/IMG_2499.jpg",
};
