import { XataHttpDatabase } from "./driver.js";
import { MigratorInitFailResponse } from "../migrator.js";
import { AnyRelations, EmptyRelations } from "../relations.js";

//#region src/xata-http/migrator.d.ts
interface MigrationConfig {
  migrationsFolder: string;
  migrationsTable?: string;
}
/**
 * This function reads migrationFolder and execute each unapplied migration and mark it as executed in database
 *
 * NOTE: The Xata HTTP driver does not support transactions. This means that if any part of a migration fails,
 * no rollback will be executed. Currently, you will need to handle unsuccessful migration yourself.
 * @param db - drizzle db instance
 * @param config - path to migration folder generated by drizzle-kit
 */
declare function migrate<TSchema extends Record<string, unknown>, TRelations extends AnyRelations = EmptyRelations>(db: XataHttpDatabase<TSchema, TRelations>, config: MigrationConfig): Promise<void | MigratorInitFailResponse>;
//#endregion
export { MigrationConfig, migrate };
//# sourceMappingURL=migrator.d.ts.map