#!/usr/bin/env tsx
import { promises as fs } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));

const ANTEATER_API = "https://anteaterapi.com/v2/rest/studyRooms";
const LIBCAL_BASES = [
	"https://spaces.lib.uci.edu/space",
	"https://scheduler.oit.uci.edu/space",
];
function weekdaysAround(anchor: Date, back: number, forward: number): string[] {
	const start = new Date(anchor);
	start.setDate(start.getDate() - back);
	const end = new Date(anchor);
	end.setDate(end.getDate() + forward);
	const dates: string[] = [];
	const cursor = new Date(start);
	while (cursor <= end) {
		const day = cursor.getDay();
		if (day !== 0 && day !== 6) {
			const yyyy = cursor.getFullYear();
			const mm = String(cursor.getMonth() + 1).padStart(2, "0");
			const dd = String(cursor.getDate()).padStart(2, "0");
			dates.push(`${yyyy}-${mm}-${dd}`);
		}
		cursor.setDate(cursor.getDate() + 1);
	}
	return dates;
}

async function fetchRoomsForDate(
	date: string,
): Promise<Array<{ id: string; name: string; location: string }> | null> {
	try {
		const url = `${ANTEATER_API}?dates=${date}&times=07:00-23:00`;
		const res = await fetch(url, { signal: AbortSignal.timeout(10000) });
		if (!res.ok) return null;
		const json = await res.json();
		return json.data ?? [];
	} catch {
		return null;
	}
}

async function fetchRoomImage(roomId: string): Promise<string | null> {
	for (const base of LIBCAL_BASES) {
		try {
			const res = await fetch(`${base}/${roomId}`, {
				headers: { "User-Agent": "Mozilla/5.0 (compatible; ZotMeet/1.0)" },
				signal: AbortSignal.timeout(8000),
			});
			if (!res.ok) continue;
			const html = await res.text();
			const match = html.match(
				/(?:https?:)?\/\/(?:s3\.amazonaws\.com\/libapps|libapps\.s3\.amazonaws\.com|[a-z0-9]+\.cloudfront\.net\/accounts)\/[^"'\s]+\.(?:jpg|jpeg|png|webp)/i,
			);
			if (match?.[0]) {
				const url = match[0].startsWith("//") ? `https:${match[0]}` : match[0];
				return url;
			}
		} catch {}
	}
	return null;
}

async function main() {
	const dates = weekdaysAround(new Date(), 7, 30);
	console.log(
		`Scanning ${dates.length} weekdays (${dates[0]} → ${dates.at(-1)}) for rooms...\n`,
	);

	const roomMap = new Map<
		string,
		{ id: string; name: string; location: string }
	>();

	let emptyStreak = 0;
	for (const date of dates) {
		process.stdout.write(`  ${date} ... `);
		const rooms = await fetchRoomsForDate(date);
		if (rooms === null) {
			console.log("fetch failed, skipping");
			continue;
		}
		const before = roomMap.size;
		for (const r of rooms) roomMap.set(r.id, r);
		const added = roomMap.size - before;
		console.log(`+${added} new (${roomMap.size} total)`);
		emptyStreak = added === 0 ? emptyStreak + 1 : 0;
		if (emptyStreak >= 3) {
			console.log("  No new rooms for 3 consecutive days — stopping early.\n");
			break;
		}
	}

	const rooms = [...roomMap.values()];
	console.log(
		`\nDiscovered ${rooms.length} unique rooms. Fetching images...\n`,
	);

	const imageMap: Record<string, string> = {};

	for (const room of rooms) {
		process.stdout.write(`  ${room.location} / ${room.name ?? room.id} ... `);
		const url = await fetchRoomImage(room.id);
		if (url) {
			imageMap[room.id] = url;
			process.stdout.write("✓\n");
		} else {
			process.stdout.write("✗\n");
		}
		await new Promise((r) => setTimeout(r, 150));
	}

	const found = Object.keys(imageMap).length;
	const lines = [
		"// Auto-generated by scripts/fetch-room-images.ts",
		`// Run \`pnpm tsx scripts/fetch-room-images.ts\` to regenerate (${found}/${rooms.length} rooms have images)`,
		"export const ROOM_IMAGES: Record<string, string> = {",
		...Object.entries(imageMap)
			.sort(([a], [b]) => a.localeCompare(b))
			.map(([id, imgUrl]) => `\t"${id}": "${imgUrl}",`),
		"};",
		"",
	].join("\n");

	const outPath = path.resolve(__dirname, "../src/lib/rooms/room-images.ts");
	await fs.writeFile(outPath, lines, "utf-8");
	console.log(`\nWrote ${found} image entries → src/lib/rooms/room-images.ts`);
}

main().catch((err) => {
	console.error(err);
	process.exit(1);
});
